#!/usr/bin/env bash
# The world's cruel

echo "$$" > /var/run/myscript.pid

trap 'echo I hate the kill command' 15 SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm /var/run/myscript.pid; kill $$' SIGQUIT SIGTERM

while :
do
	echo "To infinity and beyond"
done
