#!/usr/bin/env bash
# The world's cruel

echo "$$" > var/run/myscript.pid

while :
do
	echo "To infinity and beyond"
done
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/myscript.pid; kill $$" SIGQUIT SIGTERM
