#!/usr/bin/env bash
# Show your bash pid


for file in /proc/*/exe;
do
	process_name=$(readlink "$file")
	if [[ $process_name =~ "/bash" ]]
	then
		pid=$(echo "$file" | cut -d '/' -f 3)
		echo "$pid bash"	
	fi
done
